//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienLai
    {
        public string MaLH { get; set; }
        public string MaHV { get; set; }
        public Nullable<int> HocPhi { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual HocVien HocVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
