//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.MonHocs = new HashSet<MonHoc>();
        }
    
        public string MaGV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string ChuyenMon { get; set; }
        public string TrinhDo { get; set; }
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonHoc> MonHocs { get; set; }
        // giaovien
        public static string TangMaGV(string magv)
        {
            string[] x = magv.Split('V');
            string a = Convert.ToString(Convert.ToInt32(x[1]) + 1);
            int b = a.Length;
            if (b < 3)
                for (int i = 0; i < 3 - b; i++)
                    a = "0" + a;
            return "GV" + a;
        }
        public static bool CheckSDT(string sdt)
        {
            bool t = true;
            if (sdt.Length < 10)
                return false;
            else
            {
                for (int i = 0; i < sdt.Length; i++)
                {
                    if ('0' > sdt[i] || sdt[i] > '9')
                    {
                        t = false;
                        break;
                    }
                }
                return t;
            }

        }
    }
}
