//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocVien
    {
        public string MaHV { get; set; }
        public string MaLH { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string TinhTrang { get; set; }      
        public virtual BienLai BienLai { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        //hocvien
        public static string TangMaHV(string mahv)
        {
            string[] x = mahv.Split('V');
            string a = Convert.ToString(Convert.ToInt32(x[1]) + 1);
            int b = a.Length;
            if (b < 4)
                for (int i = 0; i < 4 - b; i++)
                    a = "0" + a;
            return "HV" + a;
        }
        public static bool CheckSDT(string sdt)
        {
            bool t = true;
            if (sdt.Length < 10)
                return false;
            else
            {
                for (int i = 0; i < sdt.Length; i++)
                {
                    if ('0' > sdt[i] || sdt[i] > '9')
                    {
                        t = false;
                        break;
                    }
                }
                return t;
            }

        }
    }
}
